import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {spawn,execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {generateKeyPairSync,randomBytes,randomUUID} from 'node:crypto';
const cli=resolve('release/node.mjs'), sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(fn){let last;for(let n=0;n<200;n++){try{const v=await fn();if(v)return v;}catch(e){last=e;}await sleep(50);}throw last??Error('job convergence timed out');}
async function freePort(){const s=createServer();s.listen(0,'127.0.0.1');await once(s,'listening');const p=s.address().port;await new Promise(r=>s.close(r));return p;}
test('quorum jobs survive a voter/runner failure, fence duplicates, retain results and fail closed',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'murakumo-jobs-'));const ps=[];
 t.after(async()=>{for(const p of ps)p.kill('SIGTERM');await sleep(150);await rm(dir,{recursive:true,force:true});});
 const key=generateKeyPairSync('ed25519'),keyFile=join(dir,'operator.pem'),pubFile=join(dir,'operator.pub'),tokenFile=join(dir,'peer-token');
 await writeFile(keyFile,key.privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});
 await writeFile(pubFile,key.publicKey.export({type:'spki',format:'pem'}));
 const token=randomBytes(32).toString('hex');await writeFile(tokenFile,token,{mode:0o600});
 const headers={authorization:'Bearer '+token,'content-type':'application/json'};
 const ids=['a','b','c','d'],ports=await Promise.all(ids.map(freePort)),urls=ports.map(p=>'http://127.0.0.1:'+p),owners=ids.map(()=>randomUUID());
 const calls=new Map();let hanging=false;
 const backend=createServer(async(req,res)=>{
  if(req.url==='/slots')return res.end('[{"is_processing":false}]');
  if(req.url==='/queue')return res.end('{"queue_running":[],"queue_pending":[]}');
  if(req.url==='/inventory')return res.end('{"CheckpointLoaderSimple":{"input":{"required":{"ckpt_name":[["test-image.safetensors"]]}}}}');
  if(req.url==='/readiness')return res.end('{"models":{"test-image":{"ready":true}}}');
  let s='';for await(const b of req)s+=b;const v=JSON.parse(s);
  const content=v.messages?.[0]?.content;
  if(content?.startsWith('2+3'))return res.end('{"choices":[{"message":{"content":"5"}}]}');
  calls.set(s,(calls.get(s)??0)+1);
  if(content==='hang'&&hanging)return;
  await sleep(120);
  res.end(JSON.stringify(req.url==='/image'?{data:[{b64_json:'aW1hZ2U='}]}:{choices:[{message:{content:'5'}}]}));
 });backend.listen(0,'127.0.0.1');await once(backend,'listening');t.after(()=>{backend.closeAllConnections();backend.close();});
 const base='http://127.0.0.1:'+backend.address().port;
 const gatewayPort=await freePort(),gatewayUrl='http://127.0.0.1:'+gatewayPort;
 const payload={schema:1,revision:1,nodes:ids.map((node,i)=>({node,url:urls[i],'owner-id':owners[i],enabled:true,roles:[{kind:'text',model:'mishima'},{kind:'image',model:'test-image'}]})),gateways:[{node:'g',url:gatewayUrl,enabled:true}],policies:{'minimum-replicas':{mishima:2,'test-image':2}}};
 const input=join(dir,'topology-input.json'),output=join(dir,'signed.json');await writeFile(input,JSON.stringify(payload));
 payload.policies['job-voters']=payload.nodes.slice(0,3).map(({node,url})=>({node,url}));await writeFile(input,JSON.stringify(payload));
 execFileSync(process.execPath,[cli,'topology','sign','--input',input,'--output',output,'--private-key-file',keyFile,'--allow-loopback','true']);
 const configs=ids.map((node,i)=>({node,bind:'127.0.0.1',port:ports[i],'token-file':tokenFile,'state-file':join(dir,node+'-receipts.json'),'legacy-empty-ledger-owner-id':owners[i],'topology-file':output,'topology-public-key-file':pubFile,'allow-loopback-topology?':true,'probe-interval-ms':1000,'topology-poll-ms':60000,'drain-file':join(dir,node+'.drain'),jobs:{directory:join(dir,node+'-jobs'),voters:payload.nodes.slice(0,3).map(({node,url})=>({node,url})),'allow-loopback?':true,'repair-ms':100},lanes:{text:{kind:'text',model:'mishima',context:32768,group:'gpu',backend:base,path:'/v1/chat/completions'},image:{kind:'image',model:'test-image',group:'gpu',backend:base,path:'/image','readiness-url':base+'/inventory'}}}));
 async function launch(i){const f=join(dir,ids[i]+'.json');await writeFile(f,JSON.stringify(configs[i]));const p=spawn(process.execPath,[cli,'up',f],{stdio:['ignore','pipe','pipe']});ps.push(p);let error='';p.stderr.on('data',b=>error+=b);p.stdout.on('data',b=>error+=b);await wait(async()=>{if(p.exitCode!==null)throw Error(error);try{return (await fetch(urls[i]+'/health',{headers})).ok;}catch{return false;}});return p;}
 for(let i=0;i<4;i++)await writeFile(configs[i]['state-file']+'.owner-id',owners[i],{mode:0o600});
 const procs=[];for(let i=0;i<4;i++)procs[i]=await launch(i);
 const json=async(i,id,body,op='')=>{const r=await fetch(urls[i]+'/jobs/'+id+op,{headers,method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};};
 const ready=async()=>wait(async()=>{const hs=await Promise.all(urls.map(async u=>{try{return await(await fetch(u+'/health',{headers})).json();}catch{return null;}}));if(!hs.filter(Boolean).every(h=>h.lanes.text.ready&&h.lanes.image.ready))throw Error(JSON.stringify(hs));return true;});await ready();
 const envelope={kind:'text',request:{model:'mishima',max_tokens:16,messages:[{role:'user',content:'qualification'}]}};
 const concurrent=await Promise.all(Array.from({length:5},(_,i)=>json(i%4,'job_concurrent',envelope)));assert.ok(concurrent.some(r=>r.status===202));
 const completed=await wait(async()=>{const r=await json(1,'job_concurrent');return r.body.receipt?.status==='completed'&&r.body;});assert.equal(completed.receipt.result.choices[0].message.content,'5');assert.equal([...calls.values()].reduce((a,b)=>a+b,0),1);
 const gatewayConfig=join(dir,'gateway.json');await writeFile(gatewayConfig,JSON.stringify({node:'g',bind:'127.0.0.1',port:gatewayPort,'token-file':tokenFile,'topology-file':output,'topology-public-key-file':pubFile,'allow-loopback-topology?':true,'probe-interval-ms':100,'topology-poll-ms':60000}));
 const gateway=spawn(process.execPath,[cli,'gateway','serve','--config',gatewayConfig],{stdio:'pipe'});ps.push(gateway);
 await wait(async()=>{try{const r=await fetch(gatewayUrl+'/jobs/job_concurrent',{headers});return r.ok&&(await r.json()).receipt?.status==='completed';}catch{return false;}});
 assert.equal((await fetch(gatewayUrl+'/jobs/job_concurrent')).status,401);
 gateway.kill('SIGTERM');await once(gateway,'exit');assert.equal((await json(3,'job_concurrent')).body.receipt.status,'completed');
 assert.equal((await json(2,'job_concurrent',{...envelope,request:{...envelope.request,max_tokens:17}})).status,503);
 for(let i=0;i<4;i++)assert.equal((await json(i,'job_concurrent',envelope)).status,202);assert.equal([...calls.values()].reduce((a,b)=>a+b,0),1);
 procs[0].kill('SIGTERM');await once(procs[0],'exit');await ready();
 assert.equal((await json(1,'job_voter_down',{kind:'image',request:{model:'test-image',prompt:'test'}})).status,202);
 await wait(async()=>{const r=await json(2,'job_voter_down');return r.body.receipt?.status==='completed';});
 assert.equal((await json(3,'job_concurrent')).body.receipt.status,'completed');
 procs[0]=await launch(0);await ready();
 procs[1].kill('SIGTERM');await once(procs[1],'exit');procs[2].kill('SIGTERM');await once(procs[2],'exit');
 assert.equal((await json(3,'job_minority',envelope)).status,503);
 assert.equal((await json(0,'job_minority')).status,503);
 procs[1]=await launch(1);procs[2]=await launch(2);await ready();
 const membership=(await(await fetch(urls[0]+'/health',{headers})).json()).jobs.membership;
 const vote=(i,op,ballot,value)=>json(i,'job_paxos',{membership,op,ballot,value},'/vote');
 const v1={owner:'a',url:urls[0],lane:'text',digest:'one'},v2={owner:'b',url:urls[1],lane:'text',digest:'two'};
 for(const i of [0,1])assert.equal((await vote(i,'accept',[1,'p'],v1)).body.ok,true);
 assert.equal((await vote(0,'accept',[1,'p'],v2)).body.ok,false);
 const prep=await Promise.all([vote(1,'prepare',[2,'q']),vote(2,'prepare',[2,'q'])]);assert.equal(prep[0].body.accepted.digest,'one');
 for(const i of [1,2])assert.equal((await vote(i,'accept',[2,'q'],v1)).body.ok,true);
 assert.equal((await vote(1,'accept',[1,'p'],v2)).body.ok,false);
 for(const [i,ballot,value] of [[0,[1,'p'],v1],[1,[2,'q'],v2],[2,[3,'r'],v1]])
  assert.equal((await json(i,'job_mixed_ballots',{membership,op:'accept',ballot,value},'/vote')).body.ok,true);
 assert.equal((await json(0,'job_mixed_ballots')).body.assignment,null,'different ballots do not prove a chosen value');
 hanging=true;await ready();assert.equal((await json(2,'job_unknown',{kind:'text',request:{model:'mishima',max_tokens:16,messages:[{role:'user',content:'hang'}]}})).status,202);
 const assignment=(await json(2,'job_unknown')).body.assignment;const owner=ids.indexOf(assignment.owner);
 await wait(async()=>{const s=JSON.parse(await readFile(join(dir,ids[owner]+'-jobs','job_unknown.json')));return s.execution?.status==='running';});
 procs[owner].kill('SIGKILL');await once(procs[owner],'exit');procs[owner]=await launch(owner);hanging=false;
 await wait(async()=>{const r=await json((owner+1)%4,'job_unknown');return r.body.receipt?.status==='unknown';});
 assert.equal((await json((owner+1)%4,'job_unknown',{kind:'text',request:{model:'mishima',max_tokens:16,messages:[{role:'user',content:'hang'}]}})).status,202);
 const hangs=[...calls.entries()].filter(([k])=>k.includes('hang'));assert.equal(hangs.reduce((n,[_,v])=>n+v,0),1);
 procs[0].kill('SIGTERM');await once(procs[0],'exit');const f=join(dir,'a-jobs','job_concurrent.json'),corrupt=JSON.parse(await readFile(f));corrupt.accepted={};await writeFile(f,JSON.stringify(corrupt));
 const bad=spawn(process.execPath,[cli,'up',join(dir,'a.json')],{stdio:'pipe'});ps.push(bad);let err='';bad.stdout.on('data',b=>err+=b);bad.stderr.on('data',b=>err+=b);await once(bad,'exit');assert.notEqual(bad.exitCode,0);assert.match(err,/invalid job ledger/);
});
