(ns murakumo.ci.broker
  "Pure broker/lease state machine for Murakumo CI. Network and persistence
   adapters store the returned state and events; clocks and lease tokens are
   explicit inputs so behavior is deterministic and portable.")

(def terminal-states #{:passed :failed :timed-out :cancelled})

(defn empty-broker []
  {:murakumo.ci/runs {}
   :murakumo.ci/queue []
   :murakumo.ci/events []})

(defn- event [state type run-id data]
  (update state :murakumo.ci/events conj
          {:ci.event/type type :ci.event/run-id run-id :ci.event/data data}))

(defn submit
  "Idempotently enqueue a run. A repeated run id leaves state unchanged."
  [state run]
  (let [id (:ci.run/id run)]
    (when-not id
      (throw (ex-info "murakumo-ci: run id required" {:reason :missing-run-id})))
    (if (get-in state [:murakumo.ci/runs id])
      state
      (-> state
          (assoc-in [:murakumo.ci/runs id]
                    (assoc run :ci.run/state :queued :ci.run/revision 0))
          (update :murakumo.ci/queue conj id)
          (event :run/submitted id nil)))))

(defn- eligible? [runner run]
  (let [required (set (:ci.run/requires run))
        offered (set (:runner/capabilities runner))]
    (every? offered required)))

(defn lease-where
  "Lease the first eligible queued run. Returns `[state lease-or-nil]`.
   `token` is generated by the host and prevents stale workers completing a
   later lease. `now-ms` and `ttl-ms` are explicit clock inputs."
  [state runner token now-ms ttl-ms predicate]
  (let [id (first (filter #(and (eligible? runner (get-in state [:murakumo.ci/runs %]))
                                (predicate % (get-in state [:murakumo.ci/runs %])))
                          (:murakumo.ci/queue state)))]
    (if-not id
      [state nil]
      (let [lease {:ci.lease/token token
                   :ci.lease/run-id id
                   :ci.lease/runner-id (:runner/id runner)
                   :ci.lease/expires-at (+ now-ms ttl-ms)}
            state' (-> state
                       (update :murakumo.ci/queue
                               (fn [q] (vec (remove #{id} q))))
                       (assoc-in [:murakumo.ci/runs id :ci.run/state] :leased)
                       (assoc-in [:murakumo.ci/runs id :ci.run/lease] lease)
                       (update-in [:murakumo.ci/runs id :ci.run/revision] inc)
                       (event :run/leased id lease))]
        [state' lease]))))

(defn lease
  [state runner token now-ms ttl-ms]
  (lease-where state runner token now-ms ttl-ms (constantly true)))

(defn- require-lease [state lease now-ms]
  (let [id (:ci.lease/run-id lease)
        current (get-in state [:murakumo.ci/runs id :ci.run/lease])]
    (when-not (= current lease)
      (throw (ex-info "murakumo-ci: stale or unknown lease"
                      {:reason :stale-lease :run/id id})))
    (when (<= (:ci.lease/expires-at lease) now-ms)
      (throw (ex-info "murakumo-ci: lease expired"
                      {:reason :lease-expired :run/id id})))
    id))

(defn start [state lease now-ms]
  (let [id (require-lease state lease now-ms)]
    (when-not (= :leased (get-in state [:murakumo.ci/runs id :ci.run/state]))
      (throw (ex-info "murakumo-ci: run is not leased"
                      {:reason :invalid-state :run/id id})))
    (-> state
        (assoc-in [:murakumo.ci/runs id :ci.run/state] :running)
        (update-in [:murakumo.ci/runs id :ci.run/revision] inc)
        (event :run/started id {:at now-ms}))))

(defn heartbeat [state lease now-ms ttl-ms]
  (let [id (require-lease state lease now-ms)
        renewed (assoc lease :ci.lease/expires-at (+ now-ms ttl-ms))]
    [(-> state
         (assoc-in [:murakumo.ci/runs id :ci.run/lease] renewed)
         (event :lease/renewed id renewed))
     renewed]))

(defn complete
  "Complete a running run with a terminal result and immutable receipt CID."
  [state lease now-ms result receipt-cid]
  (let [id (require-lease state lease now-ms)]
    (when-not (contains? terminal-states result)
      (throw (ex-info "murakumo-ci: result is not terminal"
                      {:reason :invalid-result :result result})))
    (when-not (= :running (get-in state [:murakumo.ci/runs id :ci.run/state]))
      (throw (ex-info "murakumo-ci: run is not running"
                      {:reason :invalid-state :run/id id})))
    (-> state
        (assoc-in [:murakumo.ci/runs id :ci.run/state] result)
        (assoc-in [:murakumo.ci/runs id :ci.run/receipt-cid] receipt-cid)
        (update-in [:murakumo.ci/runs id] dissoc :ci.run/lease)
        (update-in [:murakumo.ci/runs id :ci.run/revision] inc)
        (event :run/completed id {:at now-ms :result result
                                  :receipt/cid receipt-cid}))))

(defn expire
  "Requeue every expired leased/running run. Returns deterministic id order."
  [state now-ms]
  (reduce
   (fn [s id]
     (-> s
         (assoc-in [:murakumo.ci/runs id :ci.run/state] :queued)
         (update-in [:murakumo.ci/runs id] dissoc :ci.run/lease)
         (update-in [:murakumo.ci/runs id :ci.run/revision] inc)
         (update :murakumo.ci/queue conj id)
         (event :lease/expired id {:at now-ms})))
   state
   (->> (:murakumo.ci/runs state)
        (keep (fn [[id run]]
                (when (and (#{:leased :running} (:ci.run/state run))
                           (<= (get-in run [:ci.run/lease :ci.lease/expires-at]) now-ms))
                  id)))
        sort)))
