(ns murakumo.publisher
  "The fleet-plane adapter for release admission: turn a status-list credential
  into the bitmap `aiueos.publisher` reasons over, and hand it the release.

  `aiueos.publisher` decides. It takes a decoded bitmap and verified signature
  flags because it must run on a machine with no network and no JSON parser.
  Fetching the status list, verifying its own proof, and decoding it are the
  fleet plane's work — which is this namespace.

  ## The one thing worth getting right here

  `status-list.core/expand` returns **bytes**, and `aiueos.publisher/revoked?`
  indexes **bits**. The spec addresses bit `n` as byte `(quot n 8)`, bit
  `(- 7 (mod n 8))` — most-significant first inside each byte. Getting that
  backwards silently reads a different key's status, which is the failure mode
  where a revoked key looks live. `bits` uses the spec's addressing, and a test
  pins it against a list generated by the library itself rather than against a
  hand-written expectation."
  (:require [aiueos.publisher :as pub]
            [status-list.core :as sl]))

(defn bits
  "Decoded status-list bytes -> a 0/1 vector addressed the way the spec
  addresses bits. Bit n is byte (quot n 8), bit (- 7 (mod n 8))."
  [byte-vec]
  (vec (mapcat (fn [b] (map (fn [i] (if (bit-test b (- 7 i)) 1 0)) (range 8)))
               byte-vec)))

(defn credential->bits
  "A status-list credential whose own proof the caller has ALREADY verified ->
  the bitmap.

  The library's own docstring is explicit that it does not fetch or verify the
  credential, and neither does this: a status check that trusted an unverified
  list would let anyone un-revoke themselves by serving zeros. Returns nil when
  the credential carries no encoded list, and nil must not be read as \"nobody
  is revoked\" — `aiueos.publisher/revoked?` treats an index outside the bitmap
  as revoked, so passing nil fails closed by construction."
  [cred]
  (some-> (get-in cred ["credentialSubject" "encodedList"])
          sl/expand
          bits))

(defn admit
  "Admit a release, reading revocation from `status-list-credential`.

  Everything that decides is `aiueos.publisher/admit-release`; this only
  supplies the bitmap it needs. `:revocation-bits` in `state` is overwritten
  rather than merged, so a caller cannot pass a stale bitmap alongside a fresh
  credential and have the older one win."
  ([release state] (admit release state pub/default-policy))
  ([release state policy]
   (pub/admit-release release
                      (assoc state :revocation-bits
                             (credential->bits (:status-list-credential state)))
                      policy)))
